[package]
name = "s1c1"
version = "0.1.0"
authors = ["Joshua Kelly <jdjkelly@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
hex = "0.4.2"
